version: "3.7"
services:
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      - "POSTGRES_USER=$DB_USER"
      - "POSTGRES_PASSWORD=$DB_PASSWORD"
      - "POSTGRES_DB=$DB_NAME"
    volumes:
      - auth-db:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"
  api:
    build: .
    restart: always
    environment:
      - DEBUG
      - SECRET_KEY
      - ALLOWED_HOSTS
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
      - DB_PORT
      - DB_HOST
    volumes:
      - .:/home/api
    ports:
      - "80:8000"
    depends_on:
      - db
    links:
      - "db:${DB_HOST}"
    command: ["gunicorn", "--bind", ":8000", "--reload", "--log-file", "-", "-w", "4", "auth_rest_api.wsgi"]

volumes:
  auth-db:
